---
apiVersion: v1
kind: Service
metadata:
  name: mini-mirror
  namespace: ucp
  labels:
    application: promenade
    component: mini-mirror
spec:
  selector:
    application: promenade
    component: mini-mirror
  ports:
  - name: mini-mirror-port
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: mini-mirror
  namespace: ucp
  labels:
    application: promenade
    component: mini-mirror
spec:
  hostname: mini-mirror
  containers:
  - name: mini-mirorr
    image: {{ config['Genesis:images.mini-mirror'] }}
    imagePullPolicy: IfNotPresent
